name: "sigmafmt"
description: "Formatter for Sigma rules"
runs:
  using: composite
  steps:
    - run: echo $GITHUB_ACTION_PATH
      shell: bash
    - run: ls $GITHUB_ACTION_PATH
      shell: bash
    - run: ls $GITHUB_ACTION_PATH/..
      shell: bash
    - run: ls $GITHUB_ACTION_PATH/../..
      shell: bash
    - run: go run $GITHUB_ACTION_PATH/../.. --help
      shell: bash
branding:
  icon: "alert-triangle"
  color: "yellow"