name: "sigmafmt"
description: "GitHub action to run sigmafmt on all your Sigma rules"
runs:
  using: composite
  steps:
    - run: ./sigmafmt.sh
      shell: bash
      working-directory: ${{ github.action_path }}
inputs:
  path:
    description: 'The path containing Sigma rules to format. If not specified, the entire repo will be formatted'
    required: false
branding:
  icon: "alert-triangle"
  color: "yellow"