name: "sigmafmt"
description: "Formatter for Sigma rules"
runs:
  using: composite
  steps:
    - run: go run $GITHUB_ACTION_PATH/.. --help
      shell: bash
branding:
  icon: "alert-triangle"
  color: "yellow"