name: "sigmafmt"
description: "Formatter for Sigma rules"
runs:
  using: composite
  steps:
    - run: go run github.com/bradleyjkemp/sigmafmt --help
      shell: bash
branding:
  icon: "alert-triangle"
  color: "yellow"