name: "sigmafmt"
description: "Formatter for Sigma rules"
runs:
  using: composite
  steps:
    - run: ./sigmafmt.sh
      shell: bash
      working-directory: ${{ github.action_path }}
branding:
  icon: "alert-triangle"
  color: "yellow"